steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'node:18-alpine'
    entrypoint: 'npm'
    args: ['run', 'create-env']
    env:
      - 'DB_HOST=${_DB_HOST}'
      - 'DB_NAME=${_DB_NAME}'
      - 'DB_USERNAME=${_DB_USERNAME}'
      - 'DB_PASSWORD=${_DB_PASSWORD}'
      - 'ACCESS_TOKEN_SECRET=${_ACCESS_TOKEN_SECRET}'
      - 'REFRESH_TOKEN_SECRET=${_REFRESH_TOKEN_SECRET}'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nutriwise', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nutriwise']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'nutriwise', '--image', 'gcr.io/$PROJECT_ID/nutriwise', '--port', '3000', '--region', 'asia-southeast2', '--platform', 'managed', '--allow-unauthenticated']
